### ISSUE TITLE
Write a big picture description of the project

### ISSUE THREAD

**Issue by JJ** [nuciti/code#1]
Write a consensus of the project as a work document.

**Comment by NBerveglieriS3** [comment]
Presentation of the problem:

We're trying to optimize the placement of electric charging station in a city while disrupting the drivers as little as possible

The function to optimize is based on a simulation of cars going by in a city for a day. A list of cars is given at the beginning each having a departure point A (home) and an arriving point B (work) as well time of departure from each point. 

Each road is also given a %age of congestion (easy way would be 100% = you go at max speed all the way, 50% = you take 2 times longer on this road etc) giving a time of the day (lets say congestion update once every hour). Each car is also required to go at least once per day to the charging station, each station has a maximum of x cars charging at the same time and charging a car takes y minutes.

The goal is to minimize the time spent in traffic for each car while also minimizing the amount of charging station we chose to plant in an area

**Comment by JJ** [comment]
So we need data on vehicle routes in cities. That would be interesting for #3 @piotr-rarus 
We also need data on vehicle occupation in roads; some city open data portals might have that data.
We could also compute the average route lengths of cars if we have the vehicle routes.
