### ISSUE TITLE
Implemente a generator of random small-world graphs

### ISSUE THREAD

**Issue by JJ** [nuciti/code#14]
That will create the structure of the network, the weights will be evolved during the optimization process.

**Comment by JJ** [comment]
@petrrysavy @lemerleau you need to make that parametrizable; use them as parameters to the function instead of using constants.

**Comment by petrrysavy** [comment]
Done in #13 and in commit https://github.com/nuciti/code/commit/9e792a18673750c8386ad23d2c7df8086d468b45
