### ISSUE TITLE
Representation of the problem

### ISSUE THREAD

**Issue by NBerveglieriS3** [nuciti/code#6]
I think the easiest way to go about the project is treating the problem as a blackbox function.
 The solution is represented as a bitstring. Each bit represent a potential location for a charging station (0 = no charging station ; 1 = charging station). We use a simple MO(G)EA to optimize the solution. The first objective is the amount of charging station ( = amount of 1 in the bitstring) the 2nd objective is the total time spent in traffic ( addition of time spent in traffic for each car). We're thinking of FIXING the main path taken by each car because it would be otherwise too complicated. The cars chose the closest (relative to time) station.

**Comment by JJ** [comment]
Do we know in advance all possible placements for charging stations?
I think one of the papers also refers to charging station capacity, in that case it would probably not be a simple binary string?
